; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 
	nanoatmega328new
	bluepill_f103c8_usb
src_dir = src
include_dir = include

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
build_flags = -D NANO_SMT_BOARD
lib_deps = 
	mrrwa/NmraDcc@^2.0.16
	aharshac/StringSplitter@^1.0.0

[env:nanoatmega328new_KATO]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
build_flags = -D KATO_SMT_BOARD
lib_deps = 
	mrrwa/NmraDcc@^2.0.16
	aharshac/StringSplitter@^1.0.0

;[env:nanoatmega328]
;platform = atmelavr
;board = nanoatmega328
;framework = arduino
;monitor_speed = 115200
;monitor_filters = send_on_enter
;monitor_echo = yes
;lib_deps = 
;	mrrwa/NmraDcc@^2.0.16
;	aharshac/StringSplitter@^1.0.0

;[env:nanoatmega328_KATO]
;platform = atmelavr
;board = nanoatmega328
;framework = arduino
;monitor_speed = 115200
;monitor_filters = send_on_enter
;monitor_echo = yes
;build_flags = -D KATO_SMT_BOARD
;lib_deps = 
;	mrrwa/NmraDcc@^2.0.16
;	aharshac/StringSplitter@^1.0.0

;[env:ATmega328P_TQFP32]
;platform = atmelavr
;board = ATmega328P
;framework = arduino
;upload_protocol = usbtiny
;monitor_speed = 115200
;monitor_filters = send_on_enter
;monitor_echo = yes
;build_flags = -D ATMEGA328P_SMT_BOARD

;[env:ATmega328P_TQFP32_Kato]
;platform = atmelavr
;board = ATmega328P
;framework = arduino
;upload_protocol = usbtiny
;monitor_speed = 115200
;monitor_filters = send_on_enter
;monitor_echo = yes
;build_flags = -D ATMEGA328P_SMT_BOARD_KATO
;lib_deps = 
;	mrrwa/NmraDcc@^2.0.16
;	aharshac/StringSplitter@^1.0.0

;[env:ESP32]
;platform = espressif32
;board = esp32dev
;framework = arduino
;build_flags = -std=c++17
;monitor_speed = 115200
;monitor_filters = send_on_enter
;monitor_echo = yes
;lib_deps = 
;	mrrwa/NmraDcc@^2.0.16
;	aharshac/StringSplitter@^1.0.0


;[env:ESP32_38pin]
;platform = espressif32
;board = esp32dev
;framework = arduino
;build_flags = -std=c++17
;              -D ESP32_38PIN
;monitor_speed = 115200
;monitor_filters = send_on_enter
;monitor_echo = yes
;lib_deps = 
;	mrrwa/NmraDcc@^2.0.16
;	aharshac/StringSplitter@^1.0.0



[env:bluepill_f103c8_usb]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
build_flags = 
    -D STM32F1xx_Blue_Pill
	-D ARDUINO_BLUEPILL_F103C8
	-D RT_TURNOUT_DECODER
lib_deps = 
	mrrwa/NmraDcc@^2.0.16
	aharshac/StringSplitter@^1.0.0

[env:stumpy_f103c8_usb]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
build_flags = 
    -D STM32F1xx_Stumpy
	-D ARDUINO_BLUEPILL_F103C8
	-D RT_TURNOUT_DECODER
lib_deps = 
	mrrwa/NmraDcc@^2.0.16
	aharshac/StringSplitter@^1.0.0




